/**
 * AI Orchestrator Type Definitions
 * PS-05 Enterprise Intelligence Platform
 */

import type { IntentCategory } from '../router/intent.types';

/** Supported execution pipeline identifiers */
export type PipelineName =
  | 'GENERAL_PIPELINE'
  | 'ANALYTICS_PIPELINE'
  | 'BACKTEST_PIPELINE'
  | 'RETAIL_PIPELINE'
  | 'KNOWLEDGE_PIPELINE';

/** Next action designated for downstream execution */
export type NextAction =
  | 'RESPOND_DIRECTLY'
  | 'CALL_ANALYTICS_TOOL'
  | 'CALL_BACKTEST_TOOL'
  | 'CALL_PRODUCT_TOOL'
  | 'CALL_RAG';

/** Structured execution plan generated by the AI Orchestrator */
export interface ExecutionPlan {
  intent: IntentCategory;
  pipeline: PipelineName;
  selectedTool: string;
  nextAction: NextAction;
  confidence: number;
  reason: string;
  createdAt: string;
}
